### ISSUE TITLE
Script terminates after updating itself

### ISSUE THREAD

**Issue by thorsteneb** [Ornias1993/jailman#55] opened 2020-04-06 20:47 UTC
Is this as designed, or a bug? Script terminates if it has detected an update, and needs to be restarted in order to install jail.

This may be by design, as I'm not sure how it would otherwise start the updated version.

Informing the user that they should run the command again might be a good UX move.

```
root@freenas[~/jailman]# ./jailman.sh -i plex
Working directory for jailman.sh is: /root/jailman
checking for updates using Branch: dev
script requires update
HEAD is now at df5566b fix ssl path, minor language tweaks (#49)
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
Already up to date.
script updated
root@freenas[~/jailman]#
```

**Comment by Ornias1993** [comment] 2020-04-06 20:56
It should -> /dev/null the line stating `Already up to date` thats git.

The rest: yes it should be rerun. Thats by design. It should never ever rerun after an update due to security reasons.

**Comment by Ornias1993** [comment] 2020-04-06 21:08
However...
I would prefer not to have seperate issues for every missing echo line somewhere, so I created #56 as a dump for all missing/wrong/etc echo/verbosity issues. So I'll close this...

**Closed by Ornias1993** 2020-04-06 21:08 UTC
